"""SQLAlchemy ORM models for the Customer Complaint & Resolution Tracking System.

Entities (per Section 9 of the project spec):
  - Roles, Users
  - Categories
  - Complaints
  - ComplaintHistory
  - Attachments
  - Feedback
  - (extra) Notifications  — needed to fulfill Section 6.6
"""
import enum
from datetime import datetime

from sqlalchemy import (
    Column, Integer, String, Text, DateTime, ForeignKey, Boolean, Enum, Float
)
from sqlalchemy.orm import relationship

from ..core.database import Base


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------
class PriorityEnum(str, enum.Enum):
    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"
    CRITICAL = "Critical"


class StatusEnum(str, enum.Enum):
    OPEN = "Open"
    ASSIGNED = "Assigned"
    IN_PROGRESS = "In Progress"
    PENDING_CUSTOMER = "Pending Customer Response"
    ESCALATED = "Escalated"
    RESOLVED = "Resolved"
    CLOSED = "Closed"
    REOPENED = "Reopened"


# SLA rules (hours) per spec section 6.4 → resolution time per priority.
SLA_HOURS = {
    PriorityEnum.LOW: 72,
    PriorityEnum.MEDIUM: 48,
    PriorityEnum.HIGH: 24,
    PriorityEnum.CRITICAL: 4,
}


# ---------------------------------------------------------------------------
# Tables
# ---------------------------------------------------------------------------
class Role(Base):
    __tablename__ = "roles"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(50), unique=True, nullable=False)   # Admin / SupportAgent / Supervisor / Customer
    description = Column(String(255))

    users = relationship("User", back_populates="role")


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(120), nullable=False)
    email = Column(String(120), unique=True, nullable=False, index=True)
    phone = Column(String(20))
    password_hash = Column(String(255), nullable=False)
    role_id = Column(Integer, ForeignKey("roles.id"), nullable=False)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    role = relationship("Role", back_populates="users")

    complaints_created = relationship(
        "Complaint", back_populates="customer", foreign_keys="Complaint.customer_id"
    )
    complaints_assigned = relationship(
        "Complaint", back_populates="assigned_agent", foreign_keys="Complaint.assigned_agent_id"
    )
    history_entries = relationship("ComplaintHistory", back_populates="updated_by_user")


class Category(Base):
    """Complaint category — e.g. Billing, Service Disruption, etc."""
    __tablename__ = "categories"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(120), unique=True, nullable=False)
    description = Column(String(255))
    is_active = Column(Boolean, default=True)

    complaints = relationship("Complaint", back_populates="category")


class Complaint(Base):
    __tablename__ = "complaints"

    id = Column(Integer, primary_key=True, index=True)
    # CMP-YYYYMMDD-XXXX — generated by the service layer.
    complaint_number = Column(String(40), unique=True, nullable=False, index=True)

    customer_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    category_id = Column(Integer, ForeignKey("categories.id"), nullable=False)
    assigned_agent_id = Column(Integer, ForeignKey("users.id"), nullable=True)

    subject = Column(String(200), nullable=False)
    description = Column(Text, nullable=False)
    priority = Column(Enum(PriorityEnum), default=PriorityEnum.MEDIUM, nullable=False)
    status = Column(Enum(StatusEnum), default=StatusEnum.OPEN, nullable=False)

    sla_due_at = Column(DateTime, nullable=False)
    sla_breached = Column(Boolean, default=False)

    resolution_notes = Column(Text)
    resolved_at = Column(DateTime)
    closed_at = Column(DateTime)
    escalated_at = Column(DateTime)
    escalation_reason = Column(String(500))

    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    customer = relationship("User", back_populates="complaints_created", foreign_keys=[customer_id])
    assigned_agent = relationship("User", back_populates="complaints_assigned", foreign_keys=[assigned_agent_id])
    category = relationship("Category", back_populates="complaints")
    history = relationship(
        "ComplaintHistory", back_populates="complaint",
        cascade="all, delete-orphan", order_by="ComplaintHistory.updated_at.desc()"
    )
    attachments = relationship(
        "Attachment", back_populates="complaint", cascade="all, delete-orphan"
    )
    feedback = relationship(
        "Feedback", back_populates="complaint", uselist=False, cascade="all, delete-orphan"
    )


class ComplaintHistory(Base):
    """Audit trail — every status change / assignment / comment is captured here."""
    __tablename__ = "complaint_history"

    id = Column(Integer, primary_key=True, index=True)
    complaint_id = Column(Integer, ForeignKey("complaints.id", ondelete="CASCADE"), nullable=False)
    updated_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    old_status = Column(Enum(StatusEnum))
    new_status = Column(Enum(StatusEnum))
    action = Column(String(80), nullable=False)    # "created" | "assigned" | "status_change" | "comment" | ...
    comment = Column(Text)
    updated_at = Column(DateTime, default=datetime.utcnow, index=True)

    complaint = relationship("Complaint", back_populates="history")
    updated_by_user = relationship("User", back_populates="history_entries")


class Attachment(Base):
    __tablename__ = "attachments"

    id = Column(Integer, primary_key=True, index=True)
    complaint_id = Column(Integer, ForeignKey("complaints.id", ondelete="CASCADE"), nullable=False)
    file_name = Column(String(255), nullable=False)
    stored_name = Column(String(255), nullable=False)
    content_type = Column(String(100))
    size_bytes = Column(Integer)
    uploaded_by = Column(Integer, ForeignKey("users.id"))
    uploaded_at = Column(DateTime, default=datetime.utcnow)

    complaint = relationship("Complaint", back_populates="attachments")


class Feedback(Base):
    __tablename__ = "feedback"

    id = Column(Integer, primary_key=True, index=True)
    complaint_id = Column(Integer, ForeignKey("complaints.id", ondelete="CASCADE"),
                          unique=True, nullable=False)
    rating = Column(Integer, nullable=False)   # 1 - 5
    comments = Column(Text)
    submitted_at = Column(DateTime, default=datetime.utcnow)

    complaint = relationship("Complaint", back_populates="feedback")


class Notification(Base):
    __tablename__ = "notifications"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    complaint_id = Column(Integer, ForeignKey("complaints.id", ondelete="SET NULL"))
    title = Column(String(200), nullable=False)
    message = Column(Text, nullable=False)
    is_read = Column(Boolean, default=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
